[workspace]
members = [
  "concat",
  "parallelism",
  "rand_cookbook",
  "regexp",
  "command_line",
  "env_vars",
  "read_stdin",
  "var_args",
  "vector",
  "vecdequeue",
  "string",
  "ch2",
  "hashmap"
]

resolver = "2"
